### ISSUE TITLE
Cannot add new events after calling close

### ISSUE THREAD

**Issue by prabhuc94** [MuhammedKpln/peerdart#32]
![image](https://github.com/MuhammedKpln/peerdart/assets/24710386/65dcde45-4398-4506-994b-8c0c70b0b0d0)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      StreamEventEmitter.emitEvent (package:events_emitter/emitters/stream_event_emitter.dart:53:51)
#2      StreamEventEmitter.emit (package:events_emitter/emitters/stream_event_emitter.dart:92:40)
#3      Socket.start.<anonymous closure> (package:peerdart/src/socket.dart:64:7)
#4      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#8      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
#9      _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
#10     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#11     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#12     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#13     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#14     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:784:19)
#15     _StreamController._closeUnchecked (dart:async/stream_controller.dart:639:7)
#16     _StreamController.close (dart:async/stream_controller.dart:632:5)
#17     _RootZone.run (dart:async/zone.dart:1655:54)
#18     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:190:18)
#19     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:754:39)
#20     Future._propagateToListeners (dart:async/future_impl.dart:810:11)
#21     Future._completeWithValue (dart:async/future_impl.dart:584:5)
#22     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:657:7)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by azazadev** [comment]
any news ?

**Comment by dotygame** [comment]
Have you found any solutions for this problem.

**Comment by prabhuc94** [comment]
> Have you found any solutions for this problem.

No, Not yet

**Comment by dotygame** [comment]
> > Have you found any solutions for this problem.
> 
> No, Not yet

Please notify if you find any solution.

**Comment by sharkeromi** [comment]
Any update on this issue?
